### ISSUE TITLE
Create a helix command to reveal current buffer in yazi - v6

### ISSUE THREAD

**Issue by luccahuguet** [luccahuguet/yazelix#45]
evaluate if feasible before command expansion v2 lands

**Comment by luccahuguet** [comment]
https://github.com/helix-editor/helix/pull/11164

**Comment by tdaron** [comment]
Check if you can do it using macro expansions in #4709

Like this;

```
x = "@:sh your_command <C-r>%"
```

But you might want another thing that %, to discover options try to do CTRL + R inside the command prompt while typing a command

**Comment by luccahuguet** [comment]
solved in https://github.com/luccahuguet/yazelix/tree/issue_45

but depends on building helix from source

so will probably postpone this until next helix release...

**Comment by luccahuguet** [comment]
to do:

- adjust the readme
- organize a good way to share the additions to helix's config.toml, in  this case:

```toml
[keys.normal]
A-y = ":sh nu ~/.config/yazelix/nushell/reveal_in_yazi.nu \"%{buffer_name}\""
```
