### ISSUE TITLE
Add support for alacritty

### ISSUE THREAD

**Issue by DanielRivasMD** [luccahuguet/yazelix#69]
So I am a bit unclear how to run this with Alacritty. I installed all the dependencies and placed the repo in the `config` folder. The I ran the command indicated, but I feel I am missing something obvious. I do not mean to be obnoxious, but a little help would be highly appreciated.

**Comment by luccahuguet** [comment]
hey there! 

happy to help, can you give me your output?

**Comment by luccahuguet** [comment]
did you try this?

`zellij --config-dir ~/.config/yazelix/zellij attach --create yazelix_wez options --default-layout yazelix`

**Comment by luccahuguet** [comment]
issue 69, this is a special one

**Comment by myrtus0x0** [comment]
I got it working via appending this to my `alacritty.toml` 
```toml
[shell]
program = "/Users/<user>/.cargo/bin/zellij"
args = ["--config-dir", "/Users/<user>/.config/yazelix/zellij", "attach", "--create", "yazelix", "options", "--default-layout", "yazelix"]
```

Potentially related, I'm having issues with pressing enter on a file in yazi, hx isnt being found. When I exit yazi hx is able to be found and executed. So I assume nu doesn't have hx in the path.
